### ISSUE TITLE
目前有一个问题

### ISSUE THREAD

**Issue by aofall** [aofall/Public-hosts#2]
Google hosts内使用的主要ip （216.239.38.125）在大部分网络环境无法建立连接
经路由追踪发现Google似乎主动屏蔽了部分来自中国大陆的ip
因为在国际出口还没有丢包，倒是到了谷歌骨干网丢包，所以排除了墙的干扰
但 中国移动和中国电信CN2 线路则没有问题
具体问题在 https://v2ex.com/t/251690 上也有讨论

**Comment by ariable** [comment]
![tracert记录](https://ca.glory5.co/images/20160130114321.png)
这是我的tracert结果 后面全超时 到这个点断掉了
但我发现断掉的这个点用vps也ping不通 我就对断掉的该点进行tracert 在骨干网最后一跳就断掉了
上一跳209那个点本地能ping通 vps上ping不通 估计是伪造的

**Comment by aofall** [comment]
我可以正常的获取到ip上的证书，这就可以证明不是伪造的了吧
216.239.38.125是全球Anycast，大陆会分配到香港，日本会分配到日本节点

**Comment by ariable** [comment]
我这里这个ip看起来是被路由封锁了
我连证书都获取不到 tracert结果也有问题

**Comment by aofall** [comment]
你可以去 ipip.net 的[路由追踪工具][http://www.ipip.net/traceroute.php] 上选择电信cn2、移动节点，结果是正常的。
我这边的移动也是正常的，可以获取到默认证书
如果屏蔽的话为什么不全国屏蔽，这个很奇怪。

**Comment by aofall** [comment]
获取证书的前提是建立连接，如果连不上那就不用尝试了

**Comment by ariable** [comment]
这个ip在ping.chinaz.com上的结果是国内全部超时
然后我又去17ce上也是国内全部超时 奇云测也是 当然如果谷歌拒绝国内ip的话这很正常
然后我选了两个地方的联通 很神奇的是都在 74.125.37.125 断掉了
而且显示的延迟只有30-60ms 丢包0.x%
然而这个ip ping的时候根本ping不通（包括用vps ping）
而且倒数第二跳我的和那两个地方的联通一致
电信同上述情况雷同 只不过中间的跳走的电信骨干网
我换了个安徽移动 虽然最后一跳是216.239.38.125 但平均延迟才27.1ms 是不是有点假

**Comment by ariable** [comment]
而且这年头还是能扫到些www.google.com的ip的 至于通配符就真没了

**Comment by ariable** [comment]
近来扫出来一些经查询是 Youtube 的 208.65 和 208.117 的 ip 没被 block 
但证书是www.google.com 和 google.com 的
看来谷歌也缺ip

**Comment by aofall** [comment]
厄 我这里的移动现在也无法Ping通ip了
追踪也是断在谷歌骨干网上
至于伪造目标服务器返回包（tcp）这种事 @LGA1150 之前就有发现，现在是伪造目标服务器返回所有包

**Comment by aofall** [comment]
不是通配符除了手机上的应用以外是没什么事的，我这里有韩国澳门新加坡的ggc ip
hosts内用的59.18.46.20 就是韩国ggc，但近期不打算更新，除夕那天再来，看看他们的效率如何。近期216.58 新开了一些ip，我还没发现前就给办了（用的是issue里提及的方法），感觉这不科学，什么时候效率这么高了

**Comment by ariable** [comment]
神奇的事情是mtr或者tracert的时候对那个伪造的谷歌IP有延迟 单独ping不通 很令人不解 莫非tracert和ping的ICMP包不同

**Comment by aofall** [comment]
谷歌骨干网ip我记得一向是不响应ping包的
还有216.239.38.125在大陆会被Anycast到香港，在几年前谷歌香港没有被屏蔽时我ping稳定在64ms（铜线也就这样了吧？）
如果是光纤的话27ms并没有什么奇怪的吧？况且移动谷歌都接入了HKIX

**Comment by aofall** [comment]
谷歌骨干网ip我记得一向是不响应ping包的
还有216.239.38.125在大陆会被Anycast到香港，在几年前谷歌香港没有被屏蔽时我ping稳定在64ms（铜线也就这样了吧？）
如果是光纤的话27ms并没有什么奇怪的吧？况且移动谷歌都接入了HKIX

**Comment by LGA1150** [comment]
@aofall 
目前为止大陆访问谷歌香港走HKIX的只有教育网IPv6
各大运营商都有做直连

**Comment by aofall** [comment]
@LGA1150 
soga
你的原生v6是走的cernet2还是什么，我走cernet2之后还要走he.net出口
有一次还cernet2＞he.net＞hkix，延迟那叫一个高啊

**Comment by ariable** [comment]
光纤27ms当然有问题 现在并不是全光 大多都是光纤接入
我这到北京谷歌也得21ms呢
还有确实trace gce的ip Google骨干网没延迟数据
更证明我tracert的时候那个Google骨干网是伪造的

**Comment by aofall** [comment]
谷歌中国只认中国电信这一服务商
国内运营商互通那叫一个蛋疼
但现在ip已经全运营商屏蔽了（神探上的CN2未知）就是了
之前电信联通断在骨干网时，移动没问题，而且我可以正常拿到证书（建立SSL握手），这就可以证明不是伪造的了吧……
防火墙伪造目标ip还给发回正常的公匙，从没见过这种手法，一般来说是发回伪造的可信机构签名公匙进行中间人

**Comment by LGA1150** [comment]
@aofall 
谷歌中国有联通节点的GGC，不过分地区解析做得不好

**Comment by aofall** [comment]
这个我知道，但似乎没有投入使用？
用各种ping工具都是得到203.208的电信节点

**Comment by ariable** [comment]
现在Google北京肯定是BGP 因为我这连谷歌北京原来是100多ms 现在达到了极限20ms

**Comment by LGA1150** [comment]
看到hosts里的 61.49.62.49 了吗？这是北京联通的GGC

**Comment by aofall** [comment]
你的gist我有star

---

是不是BGP以tracer 结果为准吧……我在ipip.net的工具上选联通节点中间有几跳是202.97（电信骨干网）

**Comment by aofall** [comment]
对了，v2上提到的伪造ip发包不可行
如果这么做，vps是收不到各级路由返回的包的，伪造HTTP头倒是可行，但没什么卵用。
