### ISSUE TITLE
Add Google Japan and related domain.

### ISSUE THREAD

**Issue by legendtang** [aofall/Public-hosts#3]
Since many users used proxies whose provider is Japanese ISP, the default search engine for Chrome and many other browsers would be automatically set to country-based domain. Japanese proxies should be considered majority.

```
{google:baseURL}search?q=%s&{google:RLZ}{google:originalQueryForSuggestion}{google:assistedQueryStats}{google:searchFieldtrialParameter}{google:iOSSearchLanguage}{google:searchClient}{google:sourceId}{google:instantExtendedEnabledParameter}{google:contextualSearchVersion}ie={inputEncoding}
```

We don't need large hosts file but we should make sure that it should cover the majority's daily use. Thanks!

**Comment by aofall** [comment]
It will add after 9th June
You can try it by yourself

    ip google.co.jp
    ip www.google.co.jp
    ……

If you use Chrome or Firefox , please search "HSTS" and setting it on your browser

**Comment by aofall** [comment]
chrome://net-internals/#hsts

**Comment by aofall** [comment]
Done
